spring.application.name=ecommerce

# Load secrets from .env file (not pushed to GitHub)
spring.config.import=optional:file:.env[.properties]

# Database
spring.datasource.url=jdbc:mysql://localhost:3506/ecommerce_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server
server.port=8081

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000